import type { SVGProps } from "react";

/* ─────────────────────────────────────────────────────────────
   Sport glyphs drawn for FORGE: one 24-unit grid, one 1.8 stroke,
   currentColor, so a row of them reads as a set and the selected
   sport turns green with its label.

   GENERATED by scripts/sport-icons.py from the FORGE Move sport
   sprite. Edit the sprite and re-run rather than editing here.
   ───────────────────────────────────────────────────────────── */

type IconProps = SVGProps<SVGSVGElement> & { strokeWidth?: number };

const Svg = ({ children, strokeWidth = 1.8, ...p }: IconProps & { children: React.ReactNode }) => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth}
    strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...p}>{children}</svg>
);

export const RunIcon = (p: IconProps) => (
  <Svg {...p}><path d="M5 15.7c2-5.1 5.2-8.4 9.6-10.1l2 2.1-3.7 2.2 2.8 2.7-2.5 4.8H9.5" /><path d="m4.1 18.6 5.5-2.9 4.2 1.3 5.1-1.7" /><circle cx="17.5" cy="5" r="1.1" fill="currentColor" stroke="none" /></Svg>
);

export const TrailIcon = (p: IconProps) => (
  <Svg {...p}><path d="m3 18.9 5-6.1 3.5 3.1 4.2-6.2 5.3 3.3" /><path d="M4 20.4h16" /><path d="M11.9 4.2a4.2 4.2 0 0 1 3.1 5.7l-2 4.2-3.1-1.5 1.8-3.7a2 2 0 0 0-2.4-2.7" /></Svg>
);

export const WalkIcon = (p: IconProps) => (
  <Svg {...p}><path d="M7.1 4.6a3.1 3.1 0 0 1 3.1 3.1v4.5l3.8 2.8v2.9h-6l-2-4.1" /><path d="M13.7 18h5.5a1.5 1.5 0 0 1 0 3h-7" /><path d="M5.5 11.5 3.8 14" /></Svg>
);

export const HikeIcon = (p: IconProps) => (
  <Svg {...p}><path d="m2.8 19.8 5.5-7.1 3.2 2.6 4.5-6.8 5.2 4.2" /><path d="M4.4 20.7h15.2" /><path d="M10.7 5.1a3.2 3.2 0 0 1 3.2 3.2v3.1l-2.5 3.5-3.2-2.2 2.1-3.2a1.8 1.8 0 0 0-1.9-2.7" /><path d="m16.6 8.5 1.3 12.2" /></Svg>
);

export const RuckIcon = (p: IconProps) => (
  <Svg {...p}><path d="M6.2 9.5V6.8A2.8 2.8 0 0 1 9 4h4a2.8 2.8 0 0 1 2.8 2.8v2.7" /><rect x="4.2" y="8.2" width="11.4" height="11.3" rx="2.1" /><path d="M8 8.2v-2M11.8 8.2v-2M4.2 14h11.4M18.4 5.1v14.8" /><path d="M17.1 7.8h2.6" /></Svg>
);

export const RideIcon = (p: IconProps) => (
  <Svg {...p}><circle cx="5.5" cy="17" r="3.2" /><circle cx="18.5" cy="17" r="3.2" /><path d="m5.5 17 4-6h4.5l-2.1-3.1M9.5 11l4.3 6M13.2 11h3.9l1.4 6M10.7 5.1h2.9M11.6 4v3.9" /></Svg>
);

export const MtbIcon = (p: IconProps) => (
  <Svg {...p}><circle cx="5.3" cy="16.8" r="3.2" /><circle cx="18.7" cy="16.8" r="3.2" /><path d="m5.3 16.8 3.8-5.8h4.8l-2.2-3.2M9.1 11l4.5 5.8M13.3 11h3.8l1.6 5.8M2.5 21l3-2.1 2.6 1.4 3-2.7 3.2 1.7 3.5-2.5 3.3 1.4" /></Svg>
);

export const GravelIcon = (p: IconProps) => (
  <Svg {...p}><circle cx="5.5" cy="16.2" r="3" /><circle cx="18.5" cy="16.2" r="3" /><path d="m5.5 16.2 4-5.4h4.3l-2.2-3M9.5 10.8l4.1 5.4M13.1 10.8h3.9l1.5 5.4M2.7 21h2m2.4 0h2m2.4 0h2m2.4 0h2m2.4 0h2" /></Svg>
);

export const SkateIcon = (p: IconProps) => (
  <Svg {...p}><path d="M5 6.2h7.2l2.7 4.2H20l-2.5 5.1H7.4l-3-3.4Z" /><path d="M6.7 18.3h11.7" /><circle cx="8.2" cy="19.1" r="1.3" /><circle cx="12" cy="19.1" r="1.3" /><circle cx="15.8" cy="19.1" r="1.3" /></Svg>
);

export const SkiIcon = (p: IconProps) => (
  <Svg {...p}><path d="m5 8.7 4.3 2 4.4-2.2 3.7 3.2" /><path d="m8.3 5.2 2.6 5.6-2.8 4.6M14.8 5l-2.3 5.8 3.4 4.8" /><path d="M4 19.4 20 16M4.5 21 20.5 17.6" /><path d="m18.3 7.7 1.9 9.7M5.8 8.3l-2.1 9.3" /></Svg>
);

export const SkiAlpineIcon = (p: IconProps) => (
  <Svg {...p}><path d="m3 18.2 6.2-6.6 3.3 2.6 4.2-6.7 4.3 3.4" /><path d="m6 20.5 12.7-2.7M8.6 22l12.7-2.7" /><path d="M12.2 4.1 10 10l3 3.1-1.9 3.8M8.8 9.5l3.2 1.1 3.4-1.8" /></Svg>
);

export const SnowboardIcon = (p: IconProps) => (
  <Svg {...p}><path d="M3.2 18.2c4.2-2.1 10.4-4.3 17.6-6.3" /><path d="M3 18.1c-.8 1.2-.4 2.5.9 2.9M21 11.8c1.2.5 1.4 1.8.7 2.9" /><path d="m10.1 6.1-.9 4.5 3.1 1.6 3.8-1.9M6.8 9.4l2.4 1.2M12.3 8.6l3.7.4" /><circle cx="10.5" cy="4.2" r="1.1" fill="currentColor" stroke="none" /></Svg>
);

export const IceSkateIcon = (p: IconProps) => (
  <Svg {...p}><path d="M5.3 6.2h6.8l3.1 4.2h4.4l-2.4 5.1H8.1l-2.8-3.2Z" /><path d="M6.7 16.1v3.1h10.8c1.4 0 2.6-.8 3-2.1" /><path d="M6.7 21h10.8" /></Svg>
);

export const SwimIcon = (p: IconProps) => (
  <Svg {...p}><circle cx="9.2" cy="7.4" r="1.3" fill="currentColor" stroke="none" /><path d="M10.5 8.3 15 10.6l4.4-4.8M10.5 8.3 6.4 9.7 3.2 8.5" /><path d="M2.3 16.7c1.7-1.2 3.3-1.2 5 0s3.3 1.2 5 0 3.3-1.2 5 0 3.3 1.2 5 0M2.3 20c1.7-1.2 3.3-1.2 5 0s3.3 1.2 5 0 3.3-1.2 5 0 3.3 1.2 5 0" /></Svg>
);

export const RowIcon = (p: IconProps) => (
  <Svg {...p}><path d="M3 18.8h18" /><path d="M6 15.4h7.6l3.2-4.2" /><path d="m5.3 10.2 2.4 4.7 4.1.5" /><path d="m5.3 10.2 3.2-2.1 2.6 3.1" /><circle cx="6" cy="6.2" r="1.2" fill="currentColor" stroke="none" /><path d="m15.7 10.8 5-4.4M16.2 12l4.6 4.6" /></Svg>
);

export const KayakIcon = (p: IconProps) => (
  <Svg {...p}><path d="M3.1 15.6c3.6 3.6 14.2 3.6 17.8 0-3.6-1.5-14.2-1.5-17.8 0Z" /><path d="M12 6.1v6.3M8.2 8.8l7.6 3.6M5.1 6.4l13.7 7.4M5.9 13.3l-1.7-5.4M19.8 12.6l1.7 5.4" /><circle cx="12" cy="4.2" r="1.1" fill="currentColor" stroke="none" /></Svg>
);

export const SurfIcon = (p: IconProps) => (
  <Svg {...p}><path d="M3.2 17.9c4.2-1.6 11.4-4.5 17.6-7.4" /><path d="M3 18c-.7 1.1-.2 2.4 1.2 2.7M21 9.7c1.1.7 1.2 2 .4 2.9" /><path d="m10.6 6-.8 4 2.8 1.7 3.2-2M7.3 9.3l2.5.7M12.6 8.3l3.2.7" /><circle cx="10.8" cy="4.2" r="1.1" fill="currentColor" stroke="none" /></Svg>
);

export const ClimbIcon = (p: IconProps) => (
  <Svg {...p}><path d="M18.6 3v18" /><path d="m11.2 5.2-.8 5.5 2.7 2.4-.8 4.9M10.4 10.7l-3.2 2.1-1 3.6M11.2 7.2l3.8-2.5" /><circle cx="11.5" cy="3.3" r="1.2" fill="currentColor" stroke="none" /><path d="M16.4 7.2h1.4M15.1 13h1.4M16.5 18.1h1.3" /></Svg>
);

export const BoulderIcon = (p: IconProps) => (
  <Svg {...p}><path d="M3.4 6h9.1c4.3 0 7.2 2.5 7.2 6.1v1.5" /><path d="m9.7 9.2-.6 4.3 3 1.6 3.7-2.5M9.1 13.5l-3 2.1-1.2 3.1" /><circle cx="9.9" cy="7.1" r="1.2" fill="currentColor" stroke="none" /><path d="M3 20.5h18M15.7 11.8h1.5" /></Svg>
);

export const SoccerIcon = (p: IconProps) => (
  <Svg {...p}><circle cx="12" cy="12" r="8.6" /><path d="m12 7.3 3.4 2.4-1.3 4.1H9.9L8.6 9.7Z" /><path d="M12 3.4v3.9M20.5 10l-5.1-.3M17.1 19.3l-3-5.5M6.9 19.3l3-5.5M3.5 10l5.1-.3" /></Svg>
);

export const FootballIcon = (p: IconProps) => (
  <Svg {...p}><path d="M4.2 15.8c-1.2-4.7 1.7-9.1 6.4-10 4.7-.9 9.2 2 10.1 6.7.9 4.6-2.1 8.8-6.8 9.5-3.7.6-7.7-2.3-9.7-6.2Z" /><path d="m8.7 9.7 6.7 5.1M10.5 9l4.1 6.6M7.9 11.1l6.7 5.1" /></Svg>
);

export const HockeyIcon = (p: IconProps) => (
  <Svg {...p}><path d="M6.5 3.2 14.2 15" /><path d="M14.2 15c1.4 2.3 3.3 2.8 5.4 1.8" /><ellipse cx="5.6" cy="18.7" rx="3" ry="1.4" /><path d="M2.6 18.7v1.2c0 .9 1.4 1.5 3 1.5s3-.6 3-1.5v-1.2" /></Svg>
);

export const BasketballIcon = (p: IconProps) => (
  <Svg {...p}><circle cx="12" cy="12" r="8.6" /><path d="M12 3.4v17.2M3.4 12h17.2M5.9 5.9c3.1 3.3 3.1 8.9 0 12.2M18.1 5.9c-3.1 3.3-3.1 8.9 0 12.2" /></Svg>
);

export const TennisIcon = (p: IconProps) => (
  <Svg {...p}><ellipse cx="9.3" cy="8.4" rx="5.2" ry="6.1" transform="rotate(-32 9.3 8.4)" /><path d="m6.1 5.7 6.4 5.2M12.1 5.1l-5.9 6.3M13.5 13l5.3 6.7" /><circle cx="18.5" cy="6.3" r="1.7" /></Svg>
);

export const CombatIcon = (p: IconProps) => (
  <Svg {...p}><path d="M6.4 10c0-3.3 2.2-5.5 5.5-5.5h2.1c3.3 0 5.5 2.2 5.5 5.5v2.2c0 1.7-.9 3.1-2.5 3.8v2.4c0 1.1-.9 1.9-1.9 1.9H9.5c-1.1 0-1.9-.8-1.9-1.9v-2.2" /><path d="M6.4 11.9H5.1c-1.1 0-1.9.9-1.9 1.9s.8 1.9 1.9 1.9h1.3M8.4 18.1h8.4" /></Svg>
);

export const SkydiveIcon = (p: IconProps) => (
  <Svg {...p}><path d="M3.1 8.4c0-3 4-5.3 8.9-5.3s8.9 2.3 8.9 5.3" /><path d="m3.1 8.4 7 3.6M20.9 8.4 13.9 12M12 3.1V12" /><circle cx="12" cy="14.4" r="1.3" fill="currentColor" stroke="none" /><path d="M12 15.7v2.6M9.8 21l2.2-2.7 2.2 2.7" /></Svg>
);

export const ParaglideIcon = (p: IconProps) => (
  <Svg {...p}><path d="M2.5 7.1c3.4-2.7 6.6-2.7 9.5 0 3-2.7 6.1-2.7 9.5 0" /><path d="M2.5 7.1c.7 2 1.7 3.5 3.2 4.4M21.5 7.1c-.7 2-1.7 3.5-3.2 4.4M12 7.1v4.3" /><circle cx="12" cy="14.2" r="1.3" fill="currentColor" stroke="none" /><path d="M12 15.5v2.6M9.8 21l2.2-2.9 2.2 2.9" /></Svg>
);

export const OtherIcon = (p: IconProps) => (
  <Svg {...p}><path d="M2.8 12h4.1l2.1-5.5 3.7 11.1 2.2-5.6h6.3" /><circle cx="19.9" cy="6.1" r="1.5" /><path d="M19.9 3.1v1.1M19.9 8v1.1M16.9 6.1H18M21.8 6.1h1.1" /></Svg>
);
