# Regenerate src/components/sport-icons.tsx from an SVG sprite of <symbol>s.
#
#   python scripts/sport-icons.py path/to/forge-move-sport-icons.svg
#
# Each symbol id is an ActivityType ("run", "ski_alpine"…) and becomes
# RunIcon, SkiAlpineIcon… The stroke colour and width are lifted to the outer
# <svg> so the icon follows currentColor and the caller's strokeWidth.
import os, re, sys
import xml.etree.ElementTree as ET

NS = "{http://www.w3.org/2000/svg}"
DROP = {"fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"}  # set on the outer <svg>

def camel(attr):
    return re.sub(r"-([a-z])", lambda m: m.group(1).upper(), attr)

def jsx(el, top=False):
    tag = el.tag.replace(NS, "")
    if tag == "g" and top and all(k in DROP for k in el.attrib):
        return "".join(jsx(c) for c in el)
    attrs = []
    for k, v in el.attrib.items():
        # Inner defaults that merely repeat the outer ones are noise.
        if k in DROP and ((k == "stroke" and v == "currentColor") or (k == "fill" and v == "none" and tag == "g") or k in {"stroke-width", "stroke-linecap", "stroke-linejoin"}):
            continue
        attrs.append(f'{camel(k)}="{v}"')
    inner = "".join(jsx(c) for c in el)
    a = (" " + " ".join(attrs)) if attrs else ""
    return f"<{tag}{a}>{inner}</{tag}>" if inner else f"<{tag}{a} />"

def main(src):
    root = ET.parse(src).getroot()
    out = ["""import type { SVGProps } from "react";

/* ─────────────────────────────────────────────────────────────
   Sport glyphs drawn for FORGE: one 24-unit grid, one 1.8 stroke,
   currentColor, so a row of them reads as a set and the selected
   sport turns green with its label.

   GENERATED by scripts/sport-icons.py from the FORGE Move sport
   sprite. Edit the sprite and re-run rather than editing here.
   ───────────────────────────────────────────────────────────── */

type IconProps = SVGProps<SVGSVGElement> & { strokeWidth?: number };

const Svg = ({ children, strokeWidth = 1.8, ...p }: IconProps & { children: React.ReactNode }) => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth}
    strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...p}>{children}</svg>
);
"""]
    for sym in root.iter(NS + "symbol"):
        sid = sym.attrib["id"]
        name = "".join(p.capitalize() for p in sid.split("_")) + "Icon"
        body = "".join(jsx(c, top=True) for c in sym)
        out.append(f"export const {name} = (p: IconProps) => (\n  <Svg {{...p}}>{body}</Svg>\n);\n")
    dst = os.path.join(os.path.dirname(__file__), "..", "src", "components", "sport-icons.tsx")
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"{sum(1 for _ in root.iter(NS + 'symbol'))} sport icons written")

if __name__ == "__main__":
    main(sys.argv[1])
